development:
  adapter: postgresql
  encoding: unicode
  database: pf_dev
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pf_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: pf_production
  pool: 5
